### ISSUE TITLE
Errors founded in create the WDM file

### ISSUE THREAD

**Issue by xjlai** [djlampert/PyHSPF#6] opened 2018-08-01 14:01 UTC
Hi Dr. Lampert,
Thanks for this useful tools of HSPF.  
I try to use it to run HSPF model. I install the binary distributions provided in https://pypi.org/project/pyhspf/#files. 
Unfortunately, when i want to run the examples in Github. I got errors. 
For: test01.py
I got: 
-------
  File "D:/workspace/hspf/PyHSPF/examples/tests/test01.py", line 80, in <module>
    wdm.create_dataset('test.wdm', 134, attributes)
  File "D:\Softs\WinPython\python-3.6.5.amd64\lib\site-packages\pyhspf\core\wdmutil.py", line 216, in create_dataset
    raise
RuntimeError: No active exception to reraise
-------
For another examples under the folder of TEST, the same errors occured.
Any solutions?

Thank you!
Xijun Lai from Nanjing, China

**Comment by mengfeimu** [comment] 2018-08-01 15:35
Hi Xijun,

The error related to wdmutil() is usually results from wrong path to message file hspfmsg.wdm. Please check the messagepath in your script. The default setting in test01.py should be 

`messagepath = '{}/pyhspf/core/hspfmsg.wdm'.format(pyhspfdirectory)`

This path usually has more than 64 characters and that length of path is not allowed in pyhspf.

My solution is to copy pyhspf/core/hspfmsg.wdm to a short path (less than 64 characters), e.g. C:/temp/hspfmsg.wdm. And you should specify your messagepath by WDMUtil(messagepath=yourpath). Actually, this issue was solved and closed as [unable to open message file](https://github.com/djlampert/PyHSPF/issues/4) in this repo.

This should solve your problem.

Mengfei

**Comment by djlampert** [comment] 2019-02-08 00:53
Looks like this may have been resolved, so I'm going to close it out.

**Closed by djlampert** 2019-02-08 00:53 UTC

**Comment by scalet98** [comment] 2020-06-27 03:20
Thank you for good explanation !~ 
Also solved the problem by designating the messagepath path and using the below line
as you explained !~ 
wdm = WDMUtil(verbose = True, messagepath = messagepath)
:)
